### ISSUE TITLE
Нужно убрать .get()

### ISSUE THREAD

**Issue by astynax** [hexlet-components/python-immutable-fs-trees#1]
Почему [здесь](https://github.com/hexlet-components/python-immutable-fs-trees/blob/749b3c3294d6144fb4e16f2f4facddedd3a22412/src/hexlet/fs/__init__.py#L30-L52) везде обращение по ключу происходит через `.get()`? Это оправдано только для ключа `'children'`, да и то стоит возвращать пустой список, если такого ключа в словаре нет, а не `None`. Во всех остальных местах должно быть безусловное обращение по ключу. Потому что код не должен молча возвращать `None`, если у узла дерева нет того же имени.

**Comment by ramilabd** [comment]
Я взял в работу.
